### ISSUE TITLE
Chromium v64 sends many SetSelectionOwner events sent while making selection

### ISSUE THREAD

**Issue by torbiak** [cdown/clipnotify#1]
I'm running Chromium 64.0.3282.167, clipnotify 071c3d3cfec, and clipmenu caab3f6a62a. As I select text using my trackpad I see many entries being added by clipmenud, which clutters up the history when I run clipmenu. I'm inferring that Chromium sends many SetSelectionOwner events while a selection is being made, which doesn't seem to break any [ICCCM recommendations](https://tronche.com/gui/x/icccm/sec-2.html#s-2.1), but also doesn't work well with clipnotify. I can't think of a Works Every Time way to handle this. Maybe the answer is to change Chromium's behaviour. 

Oddly, I've heard that Chrome doesn't display this behaviour.

**Comment by kaihendry** [comment]
Oh I see what you are saying, you are saying that when you make a selection lots of substrings appear. I see that too in `66.0.3346.8 (Official Build) dev (64-bit)`. It doesn't bother me since I search via dmenu.

**Comment by cdown** [comment]
This is now worked around in clipmenu as  https://github.com/cdown/clipmenu/commit/0b885650fe63d7679e4fa51c06ae9511dac7af42, https://github.com/cdown/clipmenu/commit/4e969bd67dc008fe82b309a3d8a4f924bf274421, and https://github.com/cdown/clipmenu/commit/1896ceaccc921100da04744845eb17bfa23554d6

**Comment by cdown** [comment]
In terms of what to do from clipnotify's side, these events are real. It seems up to the calling party to decide what to do with the events.

This should be looked into from the Chromium side.

**Comment by cdown** [comment]
(closed without prejudice, I just think the fix has to be on Chromium side)

**Comment by cdown** [comment]
Clipmenu 5.0.0 has dedupe support back: https://github.com/cdown/clipmenu/commit/44c0fb3ad26dea8cc818d8a57aa414aecf22128d
