### ISSUE TITLE
request: empty clipboard notification

### ISSUE THREAD

**Issue by dicktyr** [cdown/clipnotify#11]
if X emits an event when the clipboard is emptied (i.e. when the owner dies)
then clipnotify could relay that to automatically restore the clipboard from history
and so solve the problem of may-be-missing contents without stealing ownership

**Comment by cdown** [comment]
Hmm, I'm not convinced this is a good idea from clipnotify -> clipmenu API side. How then is one to deal with things like password managers, where we *really* don't want to restore after clear? Once it's cleared, it's too late to get the selection owner again.

**Comment by dicktyr** [comment]
sorry, I should have composed a better title

I mean restoring/syncing from *history* which is already stored
to address the problem of clipboard persistence
without stealing ownership or overriding bindings
(which is troublesome as you've noted elsewhere)

**Comment by dicktyr** [comment]
this is working for me
```
XFixesSelectSelectionInput(disp, root, clip, XFixesSetSelectionOwnerNotifyMask | XFixesSelectionWindowDestroyNotifyMask);
```
