### ISSUE TITLE
Continuous monitor mode

### ISSUE THREAD

**Issue by nick87720z** [cdown/clipnotify#16]
The way, when command is run per each request or for each event, is somewhat ineffective. Clipnotify could stay at stdout, sending something (may be just a newline) on each event. For example, some other tools support daemon mode: inotifywait, alsactl and amixer, pacmd, skb (similar tool for xkb layout watching), free (program, not word).

If clipnotify supported such mode, it would allow to make super-effective clipmenud by moving maximum job into special utilities, arranging them into persistant pipeline, while shell would only manage its setup.
Example option: `-o, --stdout, -m, --monitor` (last two as for inotifywait).

**Comment by nick87720z** [comment]
I found better way to control it.

No need dedicated option to just enable it. Instead - very presence of any argument should trigger monitor mode. If specified - it would use it in a way similar to "yes" program, just be more selective in when to print.

The only difference from "yes" - no even concatenation is necessary, first argument should be enough (if there are spaces - they have to be quoted).

**Comment by cdown** [comment]
If I understood the feature correctly, this is implemented with `-l` for 2.0.

**Comment by nick87720z** [comment]
Nice. I did not expect other options to appear, but still would propose an argument support for crosstalking scenarios.  
(well, perhaps crosstalking could be avoided by using dedicated input).
