### ISSUE TITLE
Thank you.

### ISSUE THREAD

**Issue by g-gundam** [cdown/clipnotify#18]
This is not a bug report.  I'm just writing you to thank you for writing this very useful little program.  I was able to use it to help me write a little system for sharing clipboard contents over the network.
https://git.coom.tech/gg1234/shared-clipboard

**Comment by cdown** [comment]
you're very welcome! i just wish i had more time to work on my personal open source stuff nowadays, so it's cool to see these things being used.

**Comment by biopsin** [comment]
@cdown any chance of a release update with latest commits if stable, so I can push it to [void-repository](https://github.com/void-linux/void-packages/blob/master/srcpkgs/clipnotify/template)
