### ISSUE TITLE
arguments appear not to function

### ISSUE THREAD

**Issue by Norgus** [cdown/clipnotify#23]
I'm using the package from arch extra at https://archlinux.org/packages/extra/x86_64/clipnotify/ and am up to date with 1.0.2-2 but none of the arguments appear to do anything.

I've tried:
clipnotify -h
clipnotify --help
clipnotify -s clipboard
clipnotify -s nonsense

and more, it doesn't appear to make any difference to the behavior of the software, it just waits until a selection or clipboard event and exits. No help text, no selection/clipboard discrimination.

Let me know if I'm missing something, but this feels like a bug to me.

**Comment by dicktyr** [comment]
examining the source code for 1.0.2, one can clearly see there are no options!

**Comment by Norgus** [comment]
oh, is the readme on github about unreleased features?

**Comment by dicktyr** [comment]
@Norgus the 1.0.2 (latest) release files are 2 years old, not the currently displayed unreleased files

I already opened a request for a new release #24

**Comment by Norgus** [comment]
@dicktyr thanks for explaining, guess I'll close this!
