### ISSUE TITLE
FreeBSD Makefile changes

### ISSUE THREAD

**Issue by vendion** [cdown/clipnotify#4]
When building on FreeBSD the location of the include files for `cc` are in _/usr/local/include_ and _/usr/local/lib_. In the _Makefile_ there is already the following variable defined `x11_bsd_flags = -I/usr/X11R6/include -L/usr/X11R6/lib` which seems valid for OpenBSD

**Comment by cdown** [comment]
Sure. Feel free to submit a PR with something that works on FreeBSD. :-)

**Comment by vendion** [comment]
This seems to work for both FreeBSD and OpenBSD (not too familiar with this)

```
diff --git a/Makefile b/Makefile
index 09957af..b1cd91e 100644
--- a/Makefile
+++ b/Makefile
@@ -1,4 +1,4 @@
-x11_bsd_flags = -I/usr/X11R6/include -L/usr/X11R6/lib
+x11_bsd_flags = -I/usr/X11R6/include -I/usr/local/include -L/usr/X11R6/lib -L/usr/local/lib
 
 all:
 	${CC} ${CFLAGS} ${LDFLAGS} clipnotify.c -o clipnotify $(x11_bsd_flags) -lX11 -lXfixes
```

**Comment by cdown** [comment]
I'm going to close this for now, but if someone wants to test this in detail and it doesn't work as is now, feel free to submit a PR. :-)
