### ISSUE TITLE
Install errors on Ubuntu

### ISSUE THREAD

**Issue by winchendonsprings** [cdown/clipnotify#6]
I receive this error

```
~/.clipnotify(master ✔) make
cc   clipnotify.c -o clipnotify -I/usr/X11R6/include -L/usr/X11R6/lib -lX11 -lXfixes
clipnotify.c:1:10: fatal error: X11/Xatom.h: No such file or directory
 #include <X11/Xatom.h>
          ^~~~~~~~~~~~~
compilation terminated.
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 1
```

I'm sure the solution may be simple but I'd need to see it. Thanks

**Comment by cdown** [comment]
As the error message says, you need Xorg protocol headers. Use your usual package management tools to find out what package provides `Xatom.h` on Ubuntu. It's probably (at a guess) `x11proto-core-dev`.

**Comment by savaged** [comment]
libxfixes-dev for Ubuntu 20.04
